#!/usr/bin/env python
"""
SE_SHEETSAI — Internal BI Engine smoke test.

Usage (from project root):
  python scripts/bi_smoke_test.py

This script:
  - Loads a sample Excel file (samples/bi_sample.xlsx)
  - Ingests it into the BI runtime
  - Creates a dashboard + KPI widget
  - Executes a couple of widget queries
  - Prints results and exits non‑zero on failure
"""

import os
import sys
import json


def main() -> int:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    os.chdir(project_root)
    sys.path.insert(0, project_root)

    try:
        from dotenv import load_dotenv
        load_dotenv(os.path.join(project_root, ".env"))
    except Exception:
        pass

    from modules.db import init_db
    init_db()

    from modules.bi_engine import ingest_file_to_datasets  # type: ignore[attr-defined]
    from modules.bi_models import (
        create_dashboard_from_file,
        replace_widgets_for_dashboard,
    )
    from modules.bi_queries import execute_widget_query

    samples_dir = os.path.join(project_root, "samples")
    sample_excel = os.path.join(samples_dir, "bi_sample.xlsx")
    if not os.path.isfile(sample_excel):
        os.makedirs(samples_dir, exist_ok=True)
        try:
            import pandas as pd
            df = pd.DataFrame({"id": [1, 2, 3], "value": [10.5, 20.0, 30.5], "label": ["A", "B", "C"]})
            df.to_excel(sample_excel, index=False, sheet_name="Sheet1", engine="openpyxl")
            print(f"Created sample Excel at {sample_excel}")
        except Exception as e:
            print(f"ERROR: sample Excel not found and could not create: {e}")
            return 1

    file_id = "SMOKE_TEST_FILE"
    print(f"Ingesting sample Excel for file_id={file_id} ...")
    try:
        result = ingest_file_to_datasets(file_id, sample_excel)
    except Exception as e:  # pragma: no cover - diagnostic
        print("ERROR: ingestion failed:", e)
        return 1

    datasets = result.get("datasets") or []
    if not datasets:
        print("ERROR: ingestion returned no datasets")
        return 1
    print("Datasets:", json.dumps(datasets, ensure_ascii=False, indent=2))

    dash_id = create_dashboard_from_file(
        file_id=file_id,
        owner_user_id="smoke@test",
        title="Smoke Test Dashboard",
        description="Auto-generated by bi_smoke_test",
    )
    print("Created dashboard:", dash_id)

    ds = datasets[0]
    schema = ds.get("schema") or []
    if not schema:
        print("ERROR: dataset schema is empty")
        return 1

    # Pick first numeric column for KPI
    num_field = None
    for col in schema:
        t = str(col.get("dtype") or col.get("type") or "").lower()
        if "int" in t or "float" in t or "double" in t or "real" in t:
            num_field = col["name"]
            break
    if not num_field:
        num_field = schema[0]["name"]

    widget = {
        "widget_id": "w1",
        "type": "kpi",
        "title": f"Total {num_field}",
        "query": {
            "table": ds["table_name"],
            "dimensions": [],
            "measures": [{"field": num_field, "agg": "sum"}],
            "filters": [],
            "limit": 1,
        },
        "config": {},
    }
    replace_widgets_for_dashboard(dash_id, [widget])

    print("Executing KPI query ...")
    try:
        result = execute_widget_query(widget, user_context={"user": "smoke"})
    except Exception as e:  # pragma: no cover - diagnostic
        print("ERROR: query failed:", e)
        return 1

    print("Result:", json.dumps(result, ensure_ascii=False, indent=2))
    if not result.get("rows"):
        print("ERROR: query returned no rows")
        return 1

    print("BI smoke test completed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

